### ISSUE TITLE
Query "select * from table_foo" leads to "unsupported type 9" error

### ISSUE THREAD

**Issue by bhaskar-jain** [marcboeker/go-duckdb#106]
I am using QueryContext API to run a query of the form - "select * from table_foo" and it leads to error always. 
Using DuckDB CLI, the same query works fine against the db.  I have tried different tables with the same outcome.
The data types in my table are regular string, int and nothing fancy.

I am using DuckDB 0.4.1 and  github.com/marcboeker/go-duckdb v0.0.0-20220802072201-273b1311a677
Is this a known issue?

-Thanks.

**Comment by marcboeker** [comment]
Could you please try if the lastest version solves your problem. There was a lot of refactoring/bug fixing since August 2022.

Thanks!

**Comment by bhaskar-jain** [comment]
Many thanks for the quick response.  I tried v1.4.1 and then v1.2.3 but they were failing build since they are not compatible with the older DuckDB 0.4.1 version which I am using.  Tried v1.0.5 and this issue is not seen.

$ go get github.com/marcboeker/go-duckdb@v1.0.5
$ go mod vendor
solved this issue.

Can you please recommend which version can be used with  DuckDB 0.4.1 ?

**Comment by marcboeker** [comment]
Is there a specific reason you want to use DuckDB 0.4.1? Maybe you could migrate your existing database file to a newer version and the use the current go-duckdb driver? 
The old `go-duckdb` drivers are not recommended for further use.

**Comment by bhaskar-jain** [comment]
Thanks! Closing this issue
