### ISSUE TITLE
Append on column type UUID

### ISSUE THREAD

**Issue by crosslogic** [marcboeker/go-duckdb#108]
I have an UUID column, while trying to AppendRow() with a []byte value I get:

`couldn't append parameter 0 (type []uint8): Invalid Input Error: Failed to cast value: Unimplemented type for cast (BLOB -> UUID)`

Is there a way to do it?

**Comment by marcboeker** [comment]
The appender supports `[]byte` and `uint8` but not `[]uint8`. `[]byte` is an alias for `[]uint8`. Could you convert your UUID to `[]byte` instead of `[]uint8` or cast it via `[]byte(uuid)`?

**Comment by crosslogic** [comment]
I get the error using []byte. I understand that `byte` is actually a `uint8`

```
// byte is an alias for uint8 and is equivalent to uint8 in all ways. It is
// used, by convention, to distinguish byte values from 8-bit unsigned
// integer values.
type byte = uint8
```

**Comment by marcboeker** [comment]
Please post some more context (code, errors).

**Comment by crosslogic** [comment]
If I pass it as a `string`, it works. I think it's a DuckDB behaviour, not this driver.
It enters here:
```		
case []byte:
    rv = C.duckdb_append_blob(*a.appender, unsafe.Pointer(&v[0]), C.uint64_t(len(v)))
```

**Comment by marcboeker** [comment]
Thanks for the clarification. I'm closing this. Please reopen if you think the problem still exists.
