### ISSUE TITLE
HTTPFS - HTTP GET error on read_parquet from S3

### ISSUE THREAD

**Issue by a-agmon** [marcboeker/go-duckdb#114]
I'm executing the following statement using `db.Exec`
```sql
CREATE TABLE users AS select user_id, acc_id, email, display_name, role_name from read_parquet('s3://somebucket/perfix/00000-2280-9d8d7767-ae71-41c2-bb9c-6afe657fa26f-00001.parquet') 
```
The statement fails with 
```
HTTP Error: HTTP GET error on 'https://somebucket.s3.amazonaws.com/prefix/00000-2280-9d8d7767-ae71-41c2-bb9c-6afe657fa26f-00001.parquet' (HTTP 400)

```
The same statement succeeds using python and duck's datagrip driver (which uses JDBC I think)

running on macos with all version latest (go 1.21, duckdb 0.8.1 and duckdb-go 1.4.3)

error seems off, perhaps url is badly formatted? Am I missing something? 
(TBH - I actually think this version worked before versioned updated to go .21 but not sure)

**Comment by raulsh** [comment]
I have the exact same issue using goroutines. When I use a low number of couroutines no issue, but when a I increase the number over 5 simultaneous coroutines it fail.

SO: linux/amd64
Go: 1.19.12
go-duckdb: 1.4.4

**Comment by raulsh** [comment]
Well, I tried creating multiple DuckDB instance per Goroutine, instead of using one. And tried downloading files first, managing concurrency myself without httpfs, and works better. So I think is an DuckDB issue with httpsfs concurrency.

**Comment by marcboeker** [comment]
What error do you receive? An HTTP 400?
