### ISSUE TITLE
extensions question

### ISSUE THREAD

**Issue by gedw99** [marcboeker/go-duckdb#119]
do extensions work ? 
https://duckdb.org/docs/extensions/overview

**Comment by marcboeker** [comment]
Yes. Please have a look at:

https://github.com/marcboeker/go-duckdb/blob/0e7847abef8598e8181331a1d980592bdda0c358/duckdb_test.go#L1038C6-L1038C6

**Comment by gedw99** [comment]
Thanks

how do I load them from golang though ?

**Comment by marcboeker** [comment]
You can load the the same way as in the CLI.

```
rows, err = conn.QueryContext(context.Background(), `INSTALL 'json'; LOAD 'json';`)
```
