### ISSUE TITLE
Does DuckDB support ability to do insert into a table with MAP column type

### ISSUE THREAD

**Issue by sharad-breadfin** [marcboeker/go-duckdb#137]
https://duckdb.org/docs/archive/0.6.1/sql/data_types/map

This wiki page has some information for how to create a table with MAP column and query it. I didn't see an example of inserting a row that has map column in it. Does DuckDB have "write" support for MAP column?

**Comment by marcboeker** [comment]
@sharad-breadfin Which error do you encounter when attempting to insert data into a table containing a map column?

**Comment by sharad-breadfin** [comment]
Apologies. I should have provided more information in original post.

Error seen is:
```
converting argument $4 type: unsupported type map[string]string, a map
```

Here is code snippets:
```
type ChangeEvent struct {
	TableName           string             `parquet:"name=table_name, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	CommitTimestamp     int64              `parquet:"name=commit_timestamp, type=INT64, encoding=PLAIN"`
	TransactionId       int64              `parquet:"name=transaction_id, type=INT64, encoding=PLAIN"`        // TODO how to write UINT32 to parquet?
	Changes             *map[string]string `parquet:"name=changes, type=MAP, convertedtype=MAP, keytype=BYTE_ARRAY, keyconvertedtype=UTF8, valuetype=BYTE_ARRAY"`
}

db, _err := sql.Open("duckdb", "?access_mode=READ_WRITE")
tx, _err := db.BeginTx(ctx, nil)
_, err = tx.ExecContext(ctx, "INSERT INTO change_events"+
		"("+
		"table_name, "+
		"commit_timestamp, "+
		"transaction_id,"+
		"changes"+
		")"+
		"VALUES (?,?,?,?)",
		changeEvent.TableName,
		changeEvent.CommitTimestamp,
		changeEvent.TransactionId,
		&changeEvent.Changes,
	)
if err != nil {
		tx.Rollback()
		return fmt.Errorf("%w", err)
	}
```

**Comment by marcboeker** [comment]
@sharad-breadfin `Map` serialization is not currently available, as I'm still figuring out how to bind a map using the C-API. I will provide an update as soon as I have figured it out.

**Comment by marcboeker** [comment]
Update: Seems not possible ATM using the C-API
See: https://github.com/duckdb/duckdb/discussions/9365

You can serialize the map as JSON and store them in a VARCHAR/BLOB as a workaround.
