### ISSUE TITLE
[Question] [Bug] undefined: conn

### ISSUE THREAD

**Issue by MeowSaiGithub** [marcboeker/go-duckdb#141]
I was trying out the duckdb with this tutorial link - https://duckdb.org/docs/api/go.html  and this error came up.
```
 # github.com/marcboeker/go-duckdb
C:\Users\HP\go\pkg\mod\github.com\marcboeker\go-duckdb@v1.5.6\transaction.go:6:5: undefined: conn
```
I just use ``` go run . ``` . Did i miss anything or do anything wrong?

**Comment by marcboeker** [comment]
Unfortunately, we currently do not support Windows out of the box. There is a PR #140 for Windows support but it's not completed yet.

**Comment by MeowSaiGithub** [comment]
thanks, i thought i did something wrong

**Comment by JayanthSL** [comment]
# github.com/marcboeker/go-duckdb
C:\Users\HP\go\pkg\mod\github.com\marcboeker\go-duckdb@v1.5.6\transaction.go:6:5: undefined: conn
when will this issue be sorted for windows?
@marcboeker
