### ISSUE TITLE
Missing include for latest version of duckdb

### ISSUE THREAD

**Issue by taniabogatsch** [marcboeker/go-duckdb#158]
DuckDB's cutting-edge version removed `stdlib` from the C API header file [here](https://github.com/duckdb/duckdb/pull/10104).

This also means that go-duckdb currently does not compile with the latest version of DuckDB.

@marcboeker, the next time you deploy this driver, I expect it to fail with compiler errors such as: `could not determine kind of name for C.free`. A possible fix is to include it manually in the necessary files.
```go
/*
#include <duckdb.h>
#include <stdlib.h>
*/
import "C"
```

**Comment by marcboeker** [comment]
Thanks for the info. I think we can prepare a version that includes the `stdlib.h` with the next version upgrade of DuckDB once it's released.

**Comment by taniabogatsch** [comment]
Fixed in #163.
