### ISSUE TITLE
Is go-duckdb affected by duckdb/duckdb#10634?

### ISSUE THREAD

**Issue by michaelmdresser** [marcboeker/go-duckdb#166]
Because go-duckdb uses the C library, I'm wondering if it is affected by this issue or if it has already been addressed in go-duckdb:
- https://github.com/duckdb/duckdb/issues/10634

**Comment by taniabogatsch** [comment]
Hmm, if you `go build`, and then swap out the duckdb binaries to an older version, I think it also breaks. Same, if you use an older binary of go-duckdb with a newer binary of duckdb. But if you ensure matching versions/binaries, you avoid this issue. There is nothing to address in go-duckdb here, as it does not hard-code the enum values. You can also wait until 0.10.1, which reverts/fixes the issue.

**Comment by michaelmdresser** [comment]
Thanks for the clear explanation! Also, thank you for your contributions to the library; they have been of great help.
