### ISSUE TITLE
Support configuring duckdb

### ISSUE THREAD

**Issue by rushton** [marcboeker/go-duckdb#17]
### Issue

Unable to set configuration attributes on duckdb

### Context

The duckdb C documentation shows configuring various settings:

```
duckdb_set_config(config, "access_mode", "READ_WRITE"); // or READ_ONLY
duckdb_set_config(config, "threads", "8");
duckdb_set_config(config, "max_memory", "8GB");
duckdb_set_config(config, "default_order", "DESC");
```

settings like `access_mode` affect query concurrency, so it would be nice to be able to set these. I'm unsure how to integrate these into the database/sql interface in golang, but willing to help with some guidance.

**Comment by marcboeker** [comment]
I've looked into it and have an approach on how to support external configuration. But it will take some time to add it. In the meantime you could try to use `SET access_mode='READ_WRITE'` inside an `db.Exec()`. I think this should work.

**Comment by rushton** [comment]
Thanks! Will try that out.

**Comment by marcboeker** [comment]
I've added support for config options via query string params in the DSN. All config options on [this list](https://duckdb.org/docs/sql/configuration) are supported.

`db, err := sql.Open("duckdb", "/path/to/foo.db?access_mode=read_only&threads=4")`

Please have a look, if this solves your problem.
