### ISSUE TITLE
Make Apache Arrow Optional

### ISSUE THREAD

**Issue by ayuhito** [marcboeker/go-duckdb#204]
#134 added support for Apache Arrow but introduces a pretty heavy dependency in the process. Analysing my binaries using [`gsa`](https://github.com/Zxilly/go-size-analyzer), `github.com/apache/arrow/go/v14` introduced an additional ~800kb to my binary alone. In fact, that dependency also imports `github.com/goccy/go-json` which introduces an additional ~750kb which seems excessive if you do not use Arrow.

Would it be possible to introduce build tags and make this feature optional instead?

**Comment by ayuhito** [comment]
Perhaps dead code elimination doesn't really work if we import the database like this?

```go
import (
	_ "github.com/marcboeker/go-duckdb"
)
```

**Comment by marcboeker** [comment]
Thanks for bringing this up. We'll have a look at it. Maybe we can include the Arrow and Appender interface by default (as it is right now) and add build tags to exclude them.
