### ISSUE TITLE
 DuckDB version mismatch in v1.6.5 release

### ISSUE THREAD

**Issue by zakpaw** [marcboeker/go-duckdb#221]
As of [v1.6.5](https://github.com/marcboeker/go-duckdb/releases/tag/v1.6.5), thanks to [this PR](https://github.com/marcboeker/go-duckdb/pull/216), DuckDB should be at version 0.10.3. However, running the `SELECT version();` command returns `v0.10.2`. This issue appears to be a discrepancy between the intended DuckDB version in the release and the actual version in use.

**Comment by marcboeker** [comment]
I've created a new release, v1.6.6 that should contain 0.10.3.
