### ISSUE TITLE
how to use duckdb_vss?

### ISSUE THREAD

**Issue by loomrain** [marcboeker/go-duckdb#245]
I want to create an hnsw index and use it for vector queries, Are there any examples?

**Comment by loomrain** [comment]
DB opened with access mode read_write
panic: Binder Error: Unknown index type: HNSW

goroutine 1 [running]:
main.check(...)
	/mnt/wangqi/new_commu_frame/go-duckdb/examples/simple.go:74
main.main()
	/mnt/wangqi/new_commu_frame/go-duckdb/examples/simple.go:42 +0x98d

**Comment by marcboeker** [comment]
You need to install and load the `vss` extension first:

```
connector, err := NewConnector("", func(execer driver.ExecerContext) error {
  bootQueries := []string{
	  "INSTALL 'vss'",
	  "LOAD 'vss'",
  }
  
  for _, qry := range bootQueries {
	  _, err := execer.ExecContext(context.Background(), qry, nil)
	  if err != nil {
		  return err
	  }
  }
  return nil
})

db := sql.OpenDB(connector)
conn, err := db.Conn(context.Background())
res, err := conn.ExecContext(context.Background(), "CREATE TABLE my_vector_table (vec FLOAT[3]); CREATE INDEX my_hnsw_index ON my_vector_table USING HNSW (vec);")
```
