### ISSUE TITLE
Add support for create_function()

### ISSUE THREAD

**Issue by localhosted** [marcboeker/go-duckdb#267]
Is it possible to add support for the create_function that exists in the python API?

https://duckdb.org/docs/api/python/function.html

The C++ lib has it as well: https://duckdb.org/docs/api/cpp#udf-api

**Comment by JAicewizard** [comment]
There are PRs in the work that add table and scalar functions! Can't say when they will be merged

**Comment by taniabogatsch** [comment]
Here is the link to the respective PRs:
- scalar functions: https://github.com/marcboeker/go-duckdb/pull/222
- table functions: https://github.com/marcboeker/go-duckdb/pull/201

Please feel free to head over and look at the API; you may have some suggestions.
