### ISSUE TITLE
upgrade to Apache Arrow v17

### ISSUE THREAD

**Issue by derekperkins** [marcboeker/go-duckdb#268]
There was a recent upgrade from v14 to v15. Is there any reason not to upgrade to the latest v17 library?
https://pkg.go.dev/github.com/apache/arrow/go/v17

**Comment by marcboeker** [comment]
Hm, we're already running on v17: https://github.com/marcboeker/go-duckdb/blob/cf68f82e67168329901655c5397f32d98383674a/go.mod#L6

**Comment by derekperkins** [comment]
Sorry about that, I had this tab open for a few days, based on the v15 PR, but hadn't seen the latest one
- #252
- #263 

We're working on getting this lib supported in Bazel, and this specific dependency requires some work to support, which is why I asked. Sorry for the noise, and thanks for the great library!
- https://github.com/bazelbuild/bazel-central-registry/pull/2523

**Comment by marcboeker** [comment]
No worries and great to hear about the Bazel integration 🙂
