### ISSUE TITLE
go-duckdb@v1.8.1\transaction.go:6:5: undefined: conn

### ISSUE THREAD

**Issue by amrihuang** [marcboeker/go-duckdb#284]
when i run go build project , the problem occured.
already run    go get github.com/marcboeker/go-duckdb

the follow  code:

package main

import (
	"database/sql"
	"log"

	_ "github.com/marcboeker/go-duckdb"
)

func main() {
	db, err := sql.Open("duckdb", "")
	if (err!=nil) {
		log.Println(err)
	}
	defer db.Close()
}

**Comment by taniabogatsch** [comment]
Hi @amrihuang, have you already tried the solution suggested here: https://github.com/marcboeker/go-duckdb/issues/275?

**Comment by amrihuang** [comment]
I refer the #275 & #4[https://github.com/marcboeker/go-duckdb/issues/4](url)
and is ok now， many thanks.
