### ISSUE TITLE
Support for composite types (lists, structs, maps)

### ISSUE THREAD

**Issue by andyyu2004** [marcboeker/go-duckdb#29]
Hey, Marc!

For my use cases, I need to query composite types. I noticed this is something that isn't currently implemented, was it something that you planned to implement? I've been experimenting on a fork that adds support for this. If this is something you're interested in I'd love to get this merged. 

Unfortunately, the changes are relatively large, so I'd like to check a few things with you first. (changes can be found [here]( https://github.com/andyyu2004/go-duckdb))
- Some changes require generics and therefore go1.18. The rationale is it provides a nicer API for scanning composites. If this is something you'd prefer to not do, I'm sure I can find a way to rewrite it.
- I'll also pulled in `testify` and `sqlscan` purely for convenient testing. If you prefer to have zero dependencies, I'm happy to rewrite the tests.
- The primary change is using the duckdb `data_chunk` API instead of `duckdb_column_data` (which apparently is deprecated in favor of `data_chunk` anyway). I couldn't find a way to get composites to work otherwise.

Let me know what you think! If you're interested, I will open a PR.

**Comment by marcboeker** [comment]
Hi Andy,

thank you for adding composite types and refactoring the data fetching part. I would love to add support for this but need some time for the review. I'm not quite sure if we break a lot of projects by switching to 1.18, but to be honest I don't think it makes sense to rewrite this part without generics.

Can you please open a PR?

Thanks
Marc
