### ISSUE TITLE
transaction.go not packaged right?

### ISSUE THREAD

**Issue by yy2428** [marcboeker/go-duckdb#312]
I tried to compile an access module calling duckdb driver and get this error:
\go\pkg\mod\github.com\marcboeker\go-duckdb@v1.8.3\transaction.go:6:5: undefined: conn

It seems in transaction.go: 'type tx struct {c *conn}' is not linked to 'type conn struct {duckdbCon .duckdb_connection closed    bool	tx bool}' in connection.go.

**Comment by taniabogatsch** [comment]
Have a look at the solutions mentioned in this discussion: https://github.com/marcboeker/go-duckdb/discussions/313
