### ISSUE TITLE
Use DuckDB amalgamation instead of shared libraries

### ISSUE THREAD

**Issue by begelundmuller** [marcboeker/go-duckdb#38]
Hello! First of all, thank you for building this lovely library!

I wanted to ask if you have considered using CGo to build DuckDB from source instead of downloading and linking the DuckDB shared libraries? We cross-compile and distribute our binaries, so needing to bundle a shared library is quite the headache.

DuckDB is [available](https://duckdb.org/why_duckdb#duckdbissimple) as a single combined C++ source and header file (a so-called "amalgamation"), which should make it easy to bundle together with this repo. That would be similar to what the [go-sqlite3](https://github.com/mattn/go-sqlite3) library does (here's a direct [link](https://github.com/mattn/go-sqlite3/blob/master/sqlite3-binding.c) to the amalgamated SQLite code in the repo).

One caveat is that building DuckDB takes a while (as an example, 10 minutes on my 4-year old MacBook Pro). That would only apply when you first install the library, though. After that Go caches the build (for CI/CD, caching the builds also [appears](https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds) to be reasonably easy).

Overall, assuming this works, the pros/cons would be:

- Pros: gets rid of downloads and build flags (incl. Makefile) and you get a standalone output binary
- Cons: initial install will take several minutes

If you're interested in this, we would be very happy to develop/test it and submit it as a PR!

**Comment by begelundmuller** [comment]
I'm happy to hear that. We'd be happy to submit a PR for you to test and will try to prioritise it within a few weeks.

**Comment by begelundmuller** [comment]
This has now been merged: https://github.com/marcboeker/go-duckdb/pull/40

The PR also includes pre-compiled static libraries inspired by https://github.com/rogchap/v8go. This means that on supported platforms, you get static binaries without having to wait for DuckDB to compile.

**Comment by LasseJacobs** [comment]
@begelundmuller could you explain why having a single source file makes it easier to statically link? I thought this would not matter since in both cases (single vs multiple source files) you end up with a single archive file (.a)? But indeed I am unable to statically link the `libduckdb_static.a` file duckdb produces when I build it from source, while the archive file produced from the single file links statically without a problem.

I would like to understand why this is the case.

**Comment by begelundmuller** [comment]
Hey @LasseJacobs, you're right that simply having one source file instead of multiple source files does not itself make a difference to our ability to compile from source or statically link an archive. 

The DuckDB amalgamation is convenient because DuckDB is an extensive project with many source files and dependencies. Their build process also requires CMake and might change at any time. The point of the amalgamation is to reduce this complexity to a single file with no dependencies that can be compiled using just a C++ compiler. 

So by using the amalgamation, we both reduce build complexity and get a "contract" with the DuckDB project that's less likely to break. In fact, the amalgamation is published as part of every release, so we just [pull it](https://github.com/marcboeker/go-duckdb/blob/173119d4a701001c718d2496bceb448951ed6e80/Makefile#L17) from their release artifacts.

Now about the static library, you're right that DuckDB outputs a `libduckdb_static.a` file when you compile it from source. I actually investigated using that instead of building the static libraries from the amalgamation. However, it turns out that `libduckdb_static.a` doesn't include DuckDB's dependencies, which are compiled as separate archive files (you can find them in the build output if you search for `.a` files). You have to statically link all of them (in the right order) to make it work – which would tie us into DuckDB's current build setup, which is likely to change.

Therefore, it felt safer to just compile the amalgamation to a static library. If DuckDB ever decides to publish static libraries as part of their release artifacts (currently they only publish shared libraries), I would probably reconsider this.

**Comment by LasseJacobs** [comment]
@begelundmuller very clear now! Thanks.
