### ISSUE TITLE
windows cgo question

### ISSUE THREAD

**Issue by sdmcallister** [marcboeker/go-duckdb#4]
Sorry to ask this here. What is the proper way to set the go env in windows for this package?  I've not used cgo and I'm a bit lost and not feeling very smart. I plan on carefully reading more on cgo in the medium term but what I've read so far hasn't helped.

I've downloaded the library `libduckdb-windows-amd64` and see the following files:
```
duckdb.dll
duckdb.h
duckdb.hpp
```
Thanks for any help or advice.

**Comment by marcboeker** [comment]
Hi @sdmcallister,

as I don't have access to a Windows machine, I've tried to compile go-duckdb in a VM with the WSL. Unfortunately I'm getting an error, that the DuckDB library could not be found.

```
/usr/bin/ld: cannot find -lduckdb
collect2: error: ld returned 1 exit status
```

I think that it is not sufficient to only adjust the `CGO_LDFLAGS` and `CGO_CFLAGS` environment vars to point to the DuckDB library and header files. I've tried that and failed. There must be another way under windows to fix the library and include paths.

Unfortunately I have very little free time at the moment. Maybe you could try some Stackoverflow exploring for compiling CGO packages under the WSL and setting the CGO env vars properly.

Sorry, that I couldn't help you with this issue :(

**Comment by sdmcallister** [comment]
Thanks! I'll keep trying and if I have any success I'll be sure to post here.

**Comment by dedisuryadi** [comment]
Hope this help anyone who try to install this package on windows machine, you can try installing git-bash and mingw using chocolatey and then locate the the mingw lib directory, in my case it's on ```C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\lib``` then copy duckdb.dll there. You need to copy the duckdb header files (duckdb.h and duckdb.hpp?) to the root of go-duckdb directory, I am cloning this package btw, not installing it through go get

**Comment by sdmcallister** [comment]
@dedisuryadi  Thank for the help!

My solution was a bit different.  I used go mod.

I downloaded the recent compiled release windows 64 C/C++ release:

https://github.com/cwida/duckdb/releases/download/v0.2.5/libduckdb-windows-amd64.zip

I copied the `duckdb.h and duckdb.hpp` into 
`C:\Users\me\go\pkg\mod\github.com\marcboeker\go-duckdb@v0.0.0-20210403084307-05501463909f`

Then I copied the `duckdb.dll` into `C:\Windows\System32`

That seemed to work. Amazing! 

@marcboeker Thank you for the working on this package!

**Comment by tixsys** [comment]
here is what u miss. -lduckdb.

assuming path-to-lib is patche where .dll, .h, .lib is present correct env params will be

CGO_CFLAGS=-Ipath-to-lib
CGO_LDFLAGS=-Lpath-to-lib -lduckdb

Anddd it works on windows :)

**Comment by vdmitriyev** [comment]
Based on the valuable comment @tixsys I had created following short instructions, which worked for building and running example: [simple.go](https://github.com/marcboeker/go-duckdb/blob/main/examples/simple.go)

1. Get four files (```.dll, .lib, .hpp, .h```) from ```libduckdb-windows-amd64.zip``` archive
	+ Currently latest: https://github.com/duckdb/duckdb/releases/download/v1.0.0/libduckdb-windows-amd64.zip
2. Save them somewhere on the disk (e.g., ```c:\Soft\DuckDB\libs\```)
3. Use instructions provided by go-duckdb - https://github.com/marcboeker/go-duckdb
4. Go to your project and compile/build using ```compile.bat``` with following commands:
	```bash
	@echo off
	set PATH=c:\Soft\DuckDB\libs\;%PATH%
	set CGO_CFLAGS=-Ic:\Soft\DuckDB\libs\
	set CGO_LDFLAGS=-Lc:\Soft\DuckDB\libs\ -lduckdb
	go build
	```
