### ISSUE TITLE
Cannot execute multi-statement queries

### ISSUE THREAD

**Issue by begelundmuller** [marcboeker/go-duckdb#46]
This didn't take long, but I encountered a bug with the refactored bindings. Seems like prepared statements can't be used for multi-statement queries.

Executing a query that contains multiple statements, such as:

```go
_, err = db.Exec("INSTALL 'json'; LOAD 'json';")
if err != nil {
	fmt.Printf("error: %v", err.Error())
}
```

Outputs the following error:

```
error: Invalid Error: Cannot prepare multiple statements at once!
```

I don't know how other DB drivers deal with this, but one idea is to only use prepared statements for queries that have args? (Not sure if that has its own caveats.)

**Comment by marcboeker** [comment]
Thanks for reporting this. I've tested multiple statements with other DuckDB drivers (Rust, Python).
The Python driver [uses a very clever way](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L145) of splitting a string of multiple statements into single statements and [executing them one by one](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L152). They make use of the [`ExtractStatements` method](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb/main/connection.hpp#L103) in the C++ API.
Maybe we can leverage this?

Until we have a fix, I would suggest to merge your quick fix. Could you please open a PR?

**Comment by begelundmuller** [comment]
Yeah, I noticed the `ExtractStatements` method in the Python driver as well, unfortunately I was not able to find it in the C API. If you can't find it, do you think it makes sense to request DuckDB to add it?

I submitted a PR for my fix, but please beware that I put it together very quickly, so please double-check it before merging.

**Comment by marcboeker** [comment]
Thanks, I've tested and merged the PR.
I think we should request the `ExtractStatements` method for the C API, as this would be a cleaner solution. I'll ask them tomorrow.

**Comment by marcboeker** [comment]
I think we can close this.
