### ISSUE TITLE
Compilation failure on Linux

### ISSUE THREAD

**Issue by rongcuid** [marcboeker/go-duckdb#58]
I got massive amount of errors about libc. I thought this package uses prebundled library? It looks like it is trying to compile from source.

```
# github.com/marcboeker/go-duckdb
~/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.0.7/deps/linux_amd64/libduckdb.a(duckdb.o): In function `std::vector<duckdb::PhysicalIndex, std::allocator<duckdb::PhysicalIndex> >::operator=(std::vector<duckdb::PhysicalIndex, std::allocator<duckdb::PhysicalIndex> > const&) [clone .isra.0]':
duckdb.cpp:(.text+0x1d97e): undefined reference to `std::__throw_bad_array_new_length()'
~/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.0.7/deps/linux_amd64/libduckdb.a(duckdb.o): In function `std::vector<duckdb::LogicalType, std::allocator<duckdb::LogicalType> >::vector(std::initializer_list<duckdb::LogicalType>, std::allocator<duckdb::LogicalType> const&) [clone .constprop.0]':
duckdb.cpp:(.text+0x26bbb): undefined reference to `__libc_single_threaded'
~/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.0.7/deps/linux_amd64/libduckdb.a(duckdb.o): In function `duckdb::InitializeValidities(duckdb::Vector&, unsigned long&)':
duckdb.cpp:(.text+0x2d288): undefined reference to `__libc_single_threaded'
duckdb.cpp:(.text+0x2d30c): undefined reference to `__libc_single_threaded'
~/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.0.7/deps/linux_amd64/libduckdb.a(duckdb.o): In function `duckdb::RelationStatement::Copy() const':
duckdb.cpp:(.text+0x2e9b9): undefined reference to `__libc_single_threaded'
```

The system I am running on is old, so maybe stdc++ is also old. Not sure if it is related.

**Comment by marcboeker** [comment]
Looks like the same issue as in #54. What does your command look like to build/run your app? 

Does `make test` or `make examples` work inside the repo, when checking out on your machine?

**Comment by begelundmuller** [comment]
We are also seeing this bug, but only for DuckDB v0.6.1. I noticed that the `ubuntu-latest` Github runner moved from Ubuntu 20.04.5 to Ubuntu 22.04.01 between v0.6.0 and v0.6.1, which might be related.

It seems the problem also relates to the static libraries not being fully static, instead dynamically linking to the C++ standard library. Will investigate, but I'm not an expert on linking, so any input would be appreciated.

**Comment by marcboeker** [comment]
I've downgraded Ubuntu to 20.04 in this [branch](https://github.com/marcboeker/go-duckdb/tree/downgrade-ubuntu-runner). 

@rongcuid could you please check out this branch and try it again on your machine. If it works, we can diff the Ubuntu versions for possible changes that break the static build.

**Comment by marcboeker** [comment]
@rongcuid I've switched to clang++ instead of g++. Could you please check, if the libs in the https://github.com/marcboeker/go-duckdb/tree/switch-compiler branch now work?

**Comment by marcboeker** [comment]
Issue seems to be stale. Feel free to reopen when you have an update.
