### ISSUE TITLE
Running `install https` results in IO Error not found

### ISSUE THREAD

**Issue by chrisirhc** [marcboeker/go-duckdb#59]
I'm trying to use the httpfs extension but hitting issues.
I'm on MacOS using the latest duckdb version here ( v1.0.7 ).

Running the following:

```go
	db, err := sql.Open("duckdb", "")
	dir, err := ioutil.TempDir("", "duckdb_home")
	require.NoError(t, err)
	log.Printf("duckdb_home: %s", dir)

	_, err = db.Exec(`
	SET home_directory='` + dir + `';
	INSTALL 'httpfs';`)
	require.NoError(t, err)
```

I get:

```
	Error:      	Received unexpected error:
        	            	IO Error: Extension "/…/duckdb_home4021941023/.duckdb/extensions/v0.6.1/osx_amd64/httpfs.duckdb_extension" not found
```

**Comment by Mause** [comment]
Have you installed the extension?

**Comment by chrisirhc** [comment]
> Have you installed the extension before trying to load it?

This is the `INSTALL` command that's getting this error, not the `LOAD`.

**Comment by chrisirhc** [comment]
Urgh, this was due to bazel's sandboxing cutting off network access. Closing.
