### ISSUE TITLE
Support query cancellation and deadlines using contexts

### ISSUE THREAD

**Issue by begelundmuller** [marcboeker/go-duckdb#60]
Currently, the `go-duckdb` driver doesn't support cancelling queries when a context is cancelled. I just discovered it might be easy to add:

- By implementing [`database/sql/driver.StmtExecContext`](https://pkg.go.dev/database/sql/driver#StmtExecContext) instead of [`database/sql/driver.Stmt`](https://pkg.go.dev/database/sql/driver#Stmt), we get access to the query context and can check for cancellation.
- In [`statement.go`](https://github.com/marcboeker/go-duckdb/blob/72b078cd343c9eb3b457b279ab00838fd8ac3ce3/statement.go#L151), `duckdb_execute_prepared` is used to run a query. That will block for the duration of the entire query, which means we can't cancel a DuckDB query if the context gets cancelled. However, DuckDB provides an alternative that allows the caller to periodically regain control during query execution – it is `duckdb_pending_prepared` and related functions ([docs](https://duckdb.org/docs/api/c/api#duckdb_pending_prepared)). 

It looks like the Julia driver moved to using this ([PR](https://github.com/duckdb/duckdb/pull/4332)) to allow garbage collection to run. We could use it to periodically check the context, and cancel a query if the context has been cancelled or exceeded its deadline.

What do you think of this idea? Would be happy to submit a PR for this

**Comment by marcboeker** [comment]
It would be great to have query cancellation added. I had already created a ticket (#43) for this some time ago.
A PR would be awesome.
