### ISSUE TITLE
Querying Parquet files 

### ISSUE THREAD

**Issue by peterinfra** [marcboeker/go-duckdb#67]
I compiled the go-duckdb into a static binary and ran the example 
```
panic: Catalog Error: Table with name my.parquet does not exist!
Did you mean "pg_proc"?
LINE 1: select count(*) from 'my.parquet';
                             ^

goroutine 1 [running]:
main.check(...)
```

I modified the query to use the read_parquet function as described in the DuckDB docs and I ran into this error
```
./main
panic: Catalog Error: Function with name read_parquet is not on the catalog, but it exists in the parquet extension. To Install and Load the extension, run: INSTALL parquet; LOAD parquet;

goroutine 1 [running]:
main.check(...)
```
How does one configure this extension as a part of go-duckdb binary ?

**Comment by marcboeker** [comment]
Have you tried running `INSTALL parquet; LOAD parquet` beforehand like in https://github.com/marcboeker/go-duckdb/blob/master/duckdb_test.go#L910-L912?
