### ISSUE TITLE
Getting 403 while doing concurrent queries in S3 parquet files

### ISSUE THREAD

**Issue by nirdosh17** [marcboeker/go-duckdb#68]
**I am trying to query parquet file in S3 in Golang using this library. I have following setup:**
1. First I install and load necessary extensions `postgres_scanner` and `httpfs` and configure S3 creds: `s3_region`, `s3_secret_access_id`, `s3_secret_access_key` and `s3_session_token`

2. Then I copy selected tables from a Postgres DB and write individual tables to S3 as parquet files. No issues here.
```sql
COPY (SELECT * FROM POSTGRES_SCAN('tablename', 'public', 'pgConnUrl')) TO 's3://bucket/tablename.parquet'
```

3. Then I create views linking the parquet files in S3. No issues here as well.
```sql
CREATE OR REPLACE VIEW <table_1> AS SELECT * FROM read_parquet('s3://bucket/table_1.parquet');
CREATE OR REPLACE VIEW <table_2> AS SELECT * FROM read_parquet('s3://bucket/table_2.parquet');
```
4. Now, I query the data joining multiple tables(4-5).
```sql
SELECT * 
FROM table_1 t1 
INNER JOIN table_2 t2 on t2.user_id = t1.id
```
This works fine when I perform single query. But, when I try two or more queries concurrently, I get this error:
```shell
# bucket name redacted
Invalid Error: Unable to connect to URL "s3://<bucket>/file.parquet": 403 (Forbidden)
```
- I am pretty sure it is not related to AWS credentials expiring or not having access because it works when I perform a single query. 
- Also, there was no error when I tried querying same bucket from duckdb cli opening 4 terminal tabs concurrently. 

**Overall, It looks like rate limiting error but the 403 status code is confusing.**

Is there there is any `httpfs` config to play around? Is there any difference in the way this library breaks down queries vs  duckdb cli or other language libraries? What is the best way to debug this?

**Comment by marcboeker** [comment]
- Could you please try your use case this in the Python driver to make sure that it works there? 
- How many Goroutines are you running concurrently?
- Haye you tried using presigned URLs for your Parquet files to make sure, that circumvent possible bad credential? See: https://github.com/duckdb/duckdb/issues/5310

As we're relaying the query to DuckDB and letting DuckDB execute it, I think the only way to debug this is to include the HTTP response body to any bad requests in the error message. Not quite sure if the DuckDB developers have soimething already planned.

**Comment by nirdosh17** [comment]
Hi @marcboeker 
I am running 5-10 Goroutines concurrently. I restored to copy postgres data locally in duckdb native db file format as I did not have time to try it in Python. I will try it later when I am free again. You can close this ticket if you want.

**Comment by nirdosh17** [comment]
On a different note, I am setting up duckdb in a Go service in AWS ECS(a container service) to power the backend of an analytics page. I am getting a very slow response from the container(10-20s) even when the query itself is fast(400ms) while we run it independently. I increased container capacity as well but no luck.
Do you know similar projects where duckdb is being deployed with a containerized Go service? If you can share any references(code, documentation, github repos) related to this usecase, it would help me a lot. 
_Sorry for asking this question here. I had no other place to ask Go-Duckdb related stuff._

**Comment by marcboeker** [comment]
>  I am getting a very slow response from the container(10-20s) even when the query itself is fast(400ms) while we run it independently. I increased container capacity as well but no luck.

Are your DuckDB queries accessing third party services like S3? Is the response still slow if you do a `SELECT 1`? Please try different queries to pinpoint the problem to either the DuckDB Go driver or the query itself.

**Comment by nirdosh17** [comment]
Nope, just querying the local `.duckdb` file without any external dependencies. `SELECT 1` took around 400 ms which is higher than expected. From profiler, it can be seen that CGO call is taking long time inside container:
![Screenshot 2023-02-17 at 8 45 04 PM](https://user-images.githubusercontent.com/5920689/219689521-708c6b87-de43-470e-9ad9-11816dbde8e5.png)

I even created this barebone api with a single query and the results are similar.
https://github.com/nirdosh17/go-service-with-duckdb

**Comment by nirdosh17** [comment]
Thanks @marcboeker. That seems to be the main reason for performance degradation in my local machine. However, in ECS, I am running the container in `linux/amd64`. At the moment, I am writing the duckdb file inside the container after copying from postgres. May be there is some I/O limitation while reading the file. So, I am trying to use another storage(EFS). Let's see how it goes.

**Comment by marcboeker** [comment]
@nirdosh17 I'm going to close this issue. Feel free to reopen it, if there is a reproducible bug in go-duckdb.
