### ISSUE TITLE
Unable to scan enum typed column?

### ISSUE THREAD

**Issue by lming** [marcboeker/go-duckdb#69]
Trying to scan an enum typed column from a query row gets error `unsupported type 23` - any idea?

![image](https://user-images.githubusercontent.com/618857/215255155-e38de916-b1e5-484f-a216-d5c9d540ec32.png)

**Comment by marcboeker** [comment]
Scanning into ENUMs is not supported, as there is no corresponding native ENUM type in Go. But you could cast the column before scanning it:

```
var str string
var env string
require.NoError(t, db.QueryRow("SELECT name, CAST(environment AS text) FROM vehicles WHERE environment = ?", "Air").Scan(&str, &env))
require.Equal(t, "Aircraft", str)
require.Equal(t, "Air", env)
```
