### ISSUE TITLE
 field undefined 

### ISSUE THREAD

**Issue by liubaochuan** [marcboeker/go-duckdb#7]
../../go/pkg/mod/github.com/marcboeker/go-duckdb@v0.0.0-20210403084307-05501463909f/rows.go:70:12: val.year undefined (type _Ctype_struct___3 has no field or method year)
../../go/pkg/mod/github.com/marcboeker/go-duckdb@v0.0.0-20210403084307-05501463909f/rows.go:71:19: val.month undefined (type _Ctype_struct___3 has no field or method month)
../../go/pkg/mod/github.com/marcboeker/go-duckdb@v0.0.0-20210403084307-05501463909f/rows.go:72:12: val.day undefined (type _Ctype_struct___3 has no field or method day)
../../go/pkg/mod/github.com/marcboeker/go-duckdb@v0.0.0-20210403084307-05501463909f/statement.go:41:18: too many arguments in call to _Cfunc_duckdb_nparams

duckdb version: 0.3.0

**Comment by marcboeker** [comment]
Merged #8 to fix this. Thanks @mesge!
