### ISSUE TITLE
Implement Appender

### ISSUE THREAD

**Issue by flarco** [marcboeker/go-duckdb#70]
Hi, was looking to use the `Appender` method described here: https://duckdb.org/docs/data/appender

I figure this could be implemented in Go to use the C++ method?

I would take a stab at it, but am unfamiliar with using C methods in Go. Is this something of considerable lift?

I also noticed a bunch of lines referencing the `appender` class, here in the [duckdb.h](https://github.com/marcboeker/go-duckdb/blob/49916aa104a7d7a9d9a5479fa471c689f55c4258/duckdb.h#L1839-L2016) file.

**Comment by marcboeker** [comment]
Hi, there is already a PR open with the Appender API which you can checkout and see, if it works for you. https://github.com/marcboeker/go-duckdb/pull/37

**Comment by flarco** [comment]
Ah, missed that.
Thanks, closing.
