### ISSUE TITLE
Does this library supports querying Parquet files?

### ISSUE THREAD

**Issue by flo8** [marcboeker/go-duckdb#85]
First of all, thanks for your efforts to enable usage of DuckDB from Go!

DuckDB provides a great way to query Parquet files:
https://duckdb.org/docs/data/parquet/overview.html

Is this something planned in go-duckdb? If not, do you see a way this could be achieved?

Thanks in advance

**Comment by marcboeker** [comment]
Hi @flo8 
thanks!

You can query Parquet files like this:

```
var err error
db, err = sql.Open("duckdb", "?access_mode=READ_WRITE")
if err != nil {
    log.Fatal(err)
}
defer db.Close()

// Install and load Parquet extension
db.Exec("INSTALL parquet; LOAD parquet;") // handle error

row := db.QueryRow("SELECT * FROM read_parquet('users.parquet')")
var (
  id   int
  name string
)
row.Scan(&id, &name) // handle error
fmt.Println(id, name)
```
