### ISSUE TITLE
too many arguments in call to _Cfunc_duckdb_nparams

### ISSUE THREAD

**Issue by liubaochuan** [marcboeker/go-duckdb#9]
# github.com/marcboeker/go-duckdb
../../go/pkg/mod/github.com/marcboeker/go-duckdb@v0.0.0-20211122095031-ceaaaf0726f1/statement.go:41:18: too many arguments in call to _Cfunc_duckdb_nparams
        have (_Ctype_duckdb_prepared_statement, *_Ctype_ulonglong)
        want (_Ctype_duckdb_prepared_statement)
make: *** [build] Error 2
 
platform ：macos 
duckdb version： 0.3.0

**Comment by liubaochuan** [comment]
How to compile the library(.a file) into an executable file？

**Comment by liubaochuan** [comment]
stmt, err := db.Prepare("SELECT * FROM users WHERE age > ?")
check(err)
rows, err := stmt.Query(1)
check(err)  

The execution result error:    panic: sql: expected 0 arguments, got 1

**Comment by marcboeker** [comment]
Sorry for my late response, but I'm not able to debug this at the moment. I'll have a look at it, once I have more spare time.

**Comment by marcboeker** [comment]
Sorry for taking so long. I think it is fixed now. Please try it again with the latest version of DuckDB from their master.
