### ISSUE TITLE
how to link to duckdb library 0.8.0?

### ISSUE THREAD

**Issue by marhar** [marcboeker/go-duckdb#93]
I tried
```
go clean -cache -modcache
```
but it looks like I'm still getting duckdb 0.7.1:

```
could not open database: IO Error: Trying to read a database file with version number 51, but we can only read version 43.
```

Any hints on getting linked with duckdb 0.8.0 ?

**Comment by marcboeker** [comment]
There is currently a PR open to support DuckDB v0.8.0 but they have change something and now the linux amd64 build does not succeed. We need to fix this first.

https://github.com/marcboeker/go-duckdb/pull/92

**Comment by marhar** [comment]
Looks like everything is good, and `go get github.com/marcboeker/go-duckdb` upgraded me successfully.

Many thanks to you and all the go-duckdb team!
