### ISSUE TITLE
Build on MacOS fails with GOOS=linux

### ISSUE THREAD

**Issue by a-agmon** [marcboeker/go-duckdb#94]
im trying to build a small lambda app to be deployed in AWS container.
Im building on MacOS with 

`CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o af-bdnd-athena-query af-bdnd-athena-query.go`

and fails with 
```
# runtime/cgo
linux_syscall.c:67:13: error: call to undeclared function 'setresgid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: call to undeclared function 'setresuid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here

```

**Comment by begelundmuller** [comment]
Sadly your approach won't work because Go's cross-compilation (where you just set `GOOS` and `GOARCH`) only works for pure Go apps, not Go apps that use CGO. DuckDB is written in C++, so CGO is required.

Cross-compiling Go apps with CGO is possible, but more complicated. Google is your friend for resources. It's usually simplest just to build on the native OS and architecture (you can use a Github workflow to run builds on different runners).

**Comment by a-agmon** [comment]
Thanks @begelundmuller , 
My code compiles on ARM, and is a lambda function that is executed by AWS lambda. Lambda runtime can also be ARM so that was resolved. 
Im adding here the code for the Dockerfile I used to build it with DuckDB dynamically linked for the common good as it was not very easy to figure out.

```dockerfile
# ==== build stage ====
FROM golang:1.19.4-bullseye as build
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential wget unzip
ENV GOARCH=arm64
ENV GOOS=linux
RUN wget -qO /app/libduckdb.zip https://github.com/duckdb/duckdb/releases/download/v0.8.0/libduckdb-linux-aarch64.zip \
    && unzip -o /app/libduckdb.zip -d /app \
    && rm /app/libduckdb.zip
RUN CGO_ENABLED=1 CGO_LDFLAGS="-L/app" go build -tags=duckdb_use_lib -o mylambda mylambda.go

# ==== final stage ====
FROM debian:bullseye-slim
WORKDIR /var/task
COPY --from=build /app/mylambda ./
COPY --from=build /app/libduckdb.so /lib/
# Set the library search path
ENV LD_LIBRARY_PATH=/lib
# set the home directory
ENV HOME=/tmp
ENTRYPOINT ["/var/task/mylambda"]

```
