### ISSUE TITLE
Windows compiling error with "_access_s" error

### ISSUE THREAD

**Issue by dawsondong** [marcboeker/go-duckdb#97]
On my local windows environment, compiling any simple test go program with TDM-GCC-64 compiler will get error like the following. I did not get any similar error from other after searching. Could you please have it a look?

# github.com/marcboeker/go-duckdb
duckdb.cpp: In function 'bool duckdb_httplib::detail::is_file(const string&)':
duckdb.cpp:160873:34: error: '_access_s' was not declared in this scope
  return _access_s(path.c_str(), 0) == 0;
                                  ^

cc1plus.exe: out of memory allocating 65536 bytes

**Comment by davealexis** [comment]
Please add proper support for Windows.

**Comment by rusco** [comment]
Might help:  https://github.com/marcboeker/go-duckdb/issues/4#issuecomment-2176409066

**Comment by davealexis** [comment]
Nope. Does not work. Tried it on multiple Windows machines with the same problem. The executable at least builds with the mentioned workarounds, but just ends when the sql.Open() call is made. No panic, no error. Just ends. Has anyone actually gotten it to work even using the simple example?

**Comment by taniabogatsch** [comment]
I just merged https://github.com/marcboeker/go-duckdb/pull/248, which bundles a pre-compiled static library for Windows. It will be part of the next go-duckdb release sometime next week.

Maybe you can use the library, or build your own with the same steps as in the respective CI scripts?
